/*
* OpenAPI dependencies.
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/**
 * This module re-exports the required dependencies.
 */
export { camelCaseSync } from "https://deno.land/x/camelcase@v1.0.0/mod.ts";
