/*
* OpenAPI dependencies for oak middleware.
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/**
 * This module re-exports the required dependencies.
 */
export {
  Application,
  Request as OakRequest,
  Router,
} from "https://deno.land/x/oak@v10.2.1/mod.ts";
export type { RouterContext } from "https://deno.land/x/oak@v10.2.1/mod.ts";
