/*
* OpenAPI service to implement for User.
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
import { User } from "../models/User.ts";

export interface UserService {
  /**
   * Create user
   * This can only be done by the logged in user.
   *
   * @param user User Created user object
   * @returns void: no response value expected for this operation
   */
  createUser(user: User): Promise<void>;
  /**
   * Creates list of users with given input array
   *
   * @param user Array<User> List of user object
   * @returns void: no response value expected for this operation
   */
  createUsersWithArrayInput(user: Array<User>): Promise<void>;
  /**
   * Creates list of users with given input array
   *
   * @param user Array<User> List of user object
   * @returns void: no response value expected for this operation
   */
  createUsersWithListInput(user: Array<User>): Promise<void>;
  /**
   * Logs user into the system
   *
   * @param username string The user name for login
   * @param password string The password for login in clear text
   * @returns string
   */
  loginUser(username: string, password: string): Promise<string>;
  /**
   * Logs out current logged in user session
   *
   * @returns void: no response value expected for this operation
   */
  logoutUser(): Promise<void>;
  /**
   * Delete user
   * This can only be done by the logged in user.
   *
   * @param username string The name that needs to be deleted
   * @returns void: no response value expected for this operation
   */
  deleteUser(username: string): Promise<void>;
  /**
   * Get user by user name
   *
   * @param username string The name that needs to be fetched. Use user1 for testing.
   * @returns User
   */
  getUserByName(username: string): Promise<User>;
  /**
   * Updated user
   * This can only be done by the logged in user.
   *
   * @param username string name that need to be deleted
   * @param user User Updated user object
   * @returns void: no response value expected for this operation
   */
  updateUser(username: string, user: User): Promise<void>;
}
