/*
 * OpenAPI model for ApiResponse.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Describes the result of uploading an image resource
 */
export class ApiResponse {
  "code"?: number;
  "message"?: string;
  "type"?: string;

  constructor(
    code?: number,
    message?: string,
    type?: string,
  ) {
    this.code = code;
    this.message = message;
    this.type = type;
  }
}
