/*
* OpenAPI model for Category.
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/**
 * A category for a pet
 */
export class Category {
  "id"?: number;
  "name"?: string;

  copyFrom(anotherCategory: any): Category {
    this.id = anotherCategory.id;
    this.name = anotherCategory.name;
    return this;
  }
}
