/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A category for a pet
 */
export class Category {
  "id"?: number;
  "name"?: string;

  copyFrom(anotherCategory: any) {
    this.id = anotherCategory.id;
    this.name = anotherCategory.name;
  }
}
