/*
 * OpenAPI model for Category.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A category for a pet
 */
export class Category {
  "id"?: number;
  "name"?: string;

  constructor(
    id?: number,
    name?: string,
  ) {
    this.id = id;
    this.name = name;
  }
}
