/*
 * OpenAPI model for Order.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An order for a pets from the pet store
 */
export class Order {
  "complete"?: boolean = false;
  "id"?: number;
  "petId"?: number;
  "quantity"?: number;
  "shipDate"?: string;
  /**
   * Order Status
   */
  "status"?: StatusEnum;

  constructor(
    complete?: boolean,
    id?: number,
    petId?: number,
    quantity?: number,
    shipDate?: string,
    status?: StatusEnum,
  ) {
    this.complete = complete;
    this.id = id;
    this.petId = petId;
    this.quantity = quantity;
    this.shipDate = shipDate;
    this.status = status;
  }
}

export enum StatusEnum {
  Placed = "placed",
  Approved = "approved",
  Delivered = "delivered",
}
