/*
* OpenAPI model for Pet.
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
import { Category } from "./Category.ts";
import { Tag } from "./Tag.ts";

/**
 * A pet for sale in the pet store
 */
export class Pet {
  "id"?: number;
  "category"?: Category;
  "name": string;
  "photoUrls": Array<string>;
  "tags"?: Array<Tag>;
  /**
   * pet status in the store
   */
  "status"?: StatusEnum;

  copyFrom(anotherPet: any): Pet {
    this.id = anotherPet.id;
    this.category = anotherPet.category;
    this.name = anotherPet.name;
    this.photoUrls = anotherPet.photoUrls;
    this.tags = anotherPet.tags;
    this.status = anotherPet.status;
    return this;
  }
}

export enum StatusEnum {
  Available = "available",
  Pending = "pending",
  Sold = "sold",
}
