/*
* OpenAPI model for Tag.
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/**
 * A tag for a pet
 */
export class Tag {
  "id"?: number;
  "name"?: string;

  copyFrom(anotherTag: any): Tag {
    this.id = anotherTag.id;
    this.name = anotherTag.name;
    return this;
  }
}
