/*
 * OpenAPI model for User.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A User who is purchasing from the pet store
 */
export class User {
  "id"?: number;
  "username"?: string;
  "firstName"?: string;
  "lastName"?: string;
  "email"?: string;
  "password"?: string;
  "phone"?: string;
  /**
   * User Status
   */
  "userStatus"?: number;

  copyFrom(anotherUser: any): User {
    this.id = anotherUser.id;
    this.username = anotherUser.username;
    this.firstName = anotherUser.firstName;
    this.lastName = anotherUser.lastName;
    this.email = anotherUser.email;
    this.password = anotherUser.password;
    this.phone = anotherUser.phone;
    this.userStatus = anotherUser.userStatus;
    return this;
  }
}
