/*
 * OpenAPI model for User.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A User who is purchasing from the pet store
 */
export class User {
  "email"?: string;
  "firstName"?: string;
  "id"?: number;
  "lastName"?: string;
  "password"?: string;
  "phone"?: string;
  /**
   * User Status
   */
  "userStatus"?: number;
  "username"?: string;

  constructor(
    email?: string,
    firstName?: string,
    id?: number,
    lastName?: string,
    password?: string,
    phone?: string,
    userStatus?: number,
    username?: string,
  ) {
    this.email = email;
    this.firstName = firstName;
    this.id = id;
    this.lastName = lastName;
    this.password = password;
    this.phone = phone;
    this.userStatus = userStatus;
    this.username = username;
  }
}
