name: Build codegen then generate PetStore

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Deno
      run: curl -fsSL https://deno.land/x/install/install.sh | sh
    - name: Use Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Checkout current repo
      uses: actions/checkout@v2
      with:
        path: deno-oak-openapi-generator
    - name: Checkout OpenApi Generator repo
      uses: actions/checkout@v2
      with:
        repository: 'OpenAPITools/openapi-generator'
        path: openapi-generator
        ref: 'v6.6.0'
    - name: Set up working directory
      run: |
        mv -f openapi-generator/* .
        cp -a deno-oak-openapi-generator/. .
        rm -fr openapi-generator
        rm -fr deno-oak-openapi-generator
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Add new data into OpenApi Generator Manifest
      run: echo "org.openapitools.codegen.languages.DenoOakServerCodegen" >> ./modules/openapi-generator/src/main/resources/META-INF/services/org.openapitools.codegen.CodegenConfig
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Save PetStore for future comparison
      run: |
        mkdir petstore-backup
        cp -R samples/server/petstore/deno/ petstore-backup/
    - name: Generate Pet store
      run: |
        chmod +x ./bin/generate-samples.sh
        ./bin/generate-samples.sh bin/configs/deno-oak-server-petstore.yaml
        /home/runner/.deno/bin/deno fmt samples/server/petstore/deno/
    - name: Init Node
      run: npm ci
    - name: List generation differences
      run: diff -qr petstore-backup/deno/oak samples/server/petstore/deno/oak/
    - name: Install diff package with npm
      run: npm install dir-compare
    - name: Check generation
      uses: actions/github-script@v6
      with:
        script: |
          const dircompare = require('dir-compare');
          const res = dircompare.compareSync('petstore-backup/deno/oak', 'samples/server/petstore/deno/oak/');
          if (res.differences > 0) {
            core.setFailed('There are some generation differences');
          }