name: Postman tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * MON'
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
    - name: Install NodeJS
      run: |
        curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -
        sudo apt-get install -y nodejs
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install node packages
      run: npm i
    - name: Build Docker image for the server
      run: docker build -f ./PetStoreCompleteExample.dockerfile . -t deno-oak-petstore-server:0.1.0-beta
    - name: Launch Deno server
      run: docker run deno-oak-petstore-server:0.1.0-beta -p3000:3000
