name: Postman tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * MON'
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
    - name: Install NodeJS
      run: |
        curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -
        sudo apt-get install -y nodejs
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install node packages
      run: npm i
    - name: Build Docker image for the server
      run: |
        cd ./samples/server/petstore/deno/oak
        docker build -f ./PetStoreCompleteExample.dockerfile . -t deno-oak-petstore-server:0.1.0-beta
    - name: Launch Deno server
      run: docker run -d -p 3000:3000 --name oak-server deno-oak-petstore-server:0.1.0-beta
    - name: Sleep for 30 seconds waiting for server to start
      run: sleep 30s
      shell: bash
    - name: Launch Postman with newman
      run: |
        cd ./modules/openapi-generator/src/test/postman/deno-server/
        newman run ./PetStore\\ -\\ Dedicated\\ to\\ unit\\ tests.postman_collection.json -e ./PetStore.postman_environment.json
    - name: Stop Deno server
      run: docker stop oak-server